---
title: "Simple leniar Regression model of miles/galon against Auto/Manual transmission + a Variable selected from Mtcars Data"
author: "Lakshmi Narayana"
date: "Sunday, March 22, 2015"
output: html_document
---


# Objective

The aim of this application is to show case the relation between miles per galon and transmission to the other variables of mtcars dataset.

# Instructions on layout and usage

## Layout of the Application

- The **top panel on the left** allows for selection of **automatic/manual transmission** 
- The **bottom panel on the left** allows for selection of the **variable to plot the model** along with the automatic/manual transmission.
- The **top panel on the right** will display the **selected variables in the left panel**.
- The **middle panel on the right** will display the **mean median values of the selected variable** in the left panel from the mtcars dataset.
- The **bottom two panels on the right** will display the **summary of the model and and plot of the model** 

## Usage of the application

- User is expected to select automatic or manual transmission .default is Automatic
- User is expected to select the variable which has to included for the model along with the Transmission.

# Results

- Results are presented on the right side of the page.
- Selected variables,Summary of the selected variables,Summary and Plot of the model are displayed.

# Dataset Used is mtcars

```{r}

```
